### ISSUE TITLE
Buderus Logatherm WPL 14 AR  - energy price ratio

### ISSUE THREAD

**Issue by cossomk** [emsesp/EMS-ESP#303]
Hello!
I am using a Buderus Logatherm WPL 14 AR air heat pump + HMC300 service module + KM200 Ethernet Gateway
In the HMC300 operating module, I manually set the energy price ratio 4 times a day (there are 3 price tariffs depending on the time of day) and I would like to automate it.
Unfortunately, I did not find how to change it through the KM200 module - also the Buderus MyDevice application does not change this parameter.

Will my heat pump works with your Gateway Premium II (or other) module and can it be changed parameter automatically?
Hybrid system -> Energy price ratio
If I have the interface available I will be able to implement the change of the Energy price ratio parameter myself.

Best Regards
Mariusz

**Comment by proddy** [comment]
I can't guarantee it'll work as we haven't tested it yet. But in theory if an HMC300 allows parameters to be changed from an external device (like a MyDevice, Service key or Gateway) then EMS-ESP can replicate that as its just commands on the EMS bus.

Same with the heat-pump. There'll be a lot of trial and error, sniffing telegrams and reverse engineering so it won't be plug&play so you'll need to be brave and patient. I'd say give a shot.

Also you'll find some existing enhancement issues in the Github on how to calculate energy with examples and having Home Assistant do the heavy lifting. Nothing has been implemented yet though.
