### ISSUE TITLE
Bosch Easy Remote functionality: historical data, show vacation mode & error code, Bosch EasyService app data

### ISSUE THREAD

**Issue by joanwa** [emsesp/EMS-ESP#484]
In order to have the same information in EMS-ESP that the Bosch Easy Remote app can show, additional data needs to be extracted:

- historical data (this week, last week) for temperatures and produced solar energy
- display of vacation mode (state and end date)
- potential error code(s)

I'm currently looking into the historical data part.

Additionally the Bosch EasyService app shows a great deal of information, many of which are already parsed from EMS-ESP. Something I like there are the info buttons upon which some explanations of the value pop up - might also be useful.

Some screenshots of the apps Demo mode attached:

![app_easyService_1](https://user-images.githubusercontent.com/7691102/92399103-0602f900-f12a-11ea-8b41-9fa79ae1c098.PNG)
![app_easyService_2](https://user-images.githubusercontent.com/7691102/92399109-07ccbc80-f12a-11ea-8cb4-26d03ad977a5.PNG)
![app_easyService_3](https://user-images.githubusercontent.com/7691102/92399111-09968000-f12a-11ea-918d-e5e04e08eac8.jpg)

**Comment by proddy** [comment]
Hi @joanwa , which of these shall we add?
