### ISSUE TITLE
gb072 + rc310

### ISSUE THREAD

**Issue by Bartekn86** [emsesp/EMS-ESP#618]
hi, 
could you tell me did you remove fan modulation ?  i can not see it in new build

**Comment by proddy** [comment]
what's the name of the parameter and where is it missing (web, console, mqtt)?

**Comment by Bartekn86** [comment]
missing in web,  mqtt to. i do not remember exacly what was the name but it shows in percent speed of burners fan

**Comment by proddy** [comment]
ah ok. looks like it ran away. when did you last see it? which build?

**Comment by Bartekn86** [comment]
hm... hard to say when exacly , max 4 builds ago it works

**Comment by proddy** [comment]
do you remember the name of the parameter? It is from the boiler? There is no "fan modulation", there ar pump modulations and fan on/off in the Boiler for example.

**Comment by Bartekn86** [comment]
i do not remember. in domoticz i had value  range 0-100 %. could you give me an older version fw ? i can downgrade and check.

**Comment by proddy** [comment]
can you remember which device it was (boiler, solar, heatpump)? Also the name? Then you can look at the domocticz plugin to see what it maps too. I checked the code and can't see anything that has been removed.

**Comment by bbqkees** [comment]
@Bartekn86 There is no fan percentage device in the Domoticz plugin. There is only one on/off fan device (fanWork).

**Comment by Bartekn86** [comment]
heh, weird, I was absolutely sure there was something like that, then I misinterpreted the descriptions.
