### ISSUE TITLE
spikes on HA records

### ISSUE THREAD

**Issue by florin-laurentiu** [emsesp/EMS-ESP#709]
hello,

in HA there are every day some spikes on graphic recording of temperature, see attached picture.
i remember that it was in the past something similar , in the temperature recording of negative values if i good remember....
![download_image](https://user-images.githubusercontent.com/41485254/108636226-9a6cd800-748c-11eb-8bdf-e536ed0f8953.png)

laurentiu

**Comment by proddy** [comment]
this is from the dallas sensors? Which version are you using?

**Comment by florin-laurentiu** [comment]
hi,

i use the last development release; it is coming from boiler
sensor: sensor.boiler_burner_current_power

**Comment by proddy** [comment]
that's a %, not a temperature. Can you find what the actual value is? It comes from the 0x18 telegram (or 0xE4 for EMS+)

**Comment by florin-laurentiu** [comment]
Hello,

sure is not a temperature.....as is boiler current power...
I m not sure from where is coming...please advice what to check.

laurentiu

**Comment by proddy** [comment]
like I said, try and get some real values from the actual telegrams. Just showing a screenshot is not very helpful. You can do this using `watch 0x18`  or using syslog to record say 1hr of data.  Maybe there is a reason its spiking?

I'll also measure here to see if I can match it.
