### ISSUE TITLE
Connection status errors since upgrade

### ISSUE THREAD

**Issue by CheeseE** [emsesp/EMS-ESP#752]
**Question**
After upgrading to 2.2.1, EMS connection issues appear on the dashboard and commands are not sent to the boiler.
Boiler is a Junkers Cerapur Smart ZSB14-C.

**Screenshots**
![image](https://user-images.githubusercontent.com/6362450/112341610-da102500-8cc1-11eb-88e8-c703d9538131.png)

**Device information**
"Settings": {
    "tx_mode": 3,
    "ems_bus_id": 11,
    "syslog_level": -1,
    "syslog_mark_interval": 0,
    "syslog_host": "",
    "master_thermostat": 0,
    "shower_timer": "on",
    "shower_alert": "off",
    "rx_gpio": 13,
    "tx_gpio": 15,
    "dallas_gpio": 14,
    "dallas_parasite": "off",
    "led_gpio": 2,
    "hide_led": "off",
    "api_enabled": "on",
    "bool_format": 1,
    "analog_enabled": "off"
  }

**Additional context**
I have tried to roll back to previous working versions(2.2.0,2.10), and those are also having issues now. Nothing changed in the setup, also tried to restart both the gateway and boiler, but still the same. Also tried with different TX mode, but nothing works.
Should I try factory reset or changing the cable?

**Comment by proddy** [comment]
that is odd. Could you do a http://ems-esp/api?device=system&cmd=info so we can see number of tx fails. Are you powering via USB, Jack or the EMS lines?
